### ISSUE TITLE
Required podfile is missing from the repository

### ISSUE THREAD

**Issue by ee0pdt** [TryxAPI/activity-tracker-xapi#1]
Hi there and thank you for making your code available. I have attempted to compile the project and it appears that the libPods library is missing and the podfile that would generate this file is also missing.

I have attempted to recreate a valid podfile myself, but the resulting workspace does not link or compile.

Would you be able to commit and push the podfile and associated pod directory?

**Comment by vbudhram** [comment]
Hey @ee0pdt, thanks for checking out the repo! I create a PR #2 that address the issue. However, if you wanted to try it out, you can check out the branch directly.

**Comment by ee0pdt** [comment]
Hi there, that's perfect, I checked out the branch and made a successful build.
